# Website Domain Scraper Configuration

# URL to start crawling from (required)
start_url: https://topai.tools/category/travel

# Maximum number of pages to crawl (default: 100)
max_pages: 100

# Delay between requests in seconds (default: 0.5)
request_delay: 0.5

# Enable verbose logging (default: false)
verbose: true 